# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages:
  - dplyr
  - gh
  - ggplot2
  - xtable

r_github_packages:
  - ropensci/spelling

after_script:
  - Rscript -e 'spelling::spell_check_files("introduction.tex", ignore = readLines("inst/WORDLIST"))'
  # Same, but gives an error if spellcheck fails
  - [ "$(Rscript -e 'spelling::spell_check_files("introduction.tex", ignore = readLines("inst/WORDLIST"))')" == "No spelling errors found." ]

